defmodule Choreocal.Repo.Migrations.AddPlanner do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:class_exercises, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :cues, :text
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "class_exercises_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :section_id, :uuid, null: false
      add :exercise_id, :uuid
    end

    create table(:class_sections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:class_exercises) do
      modify :section_id,
             references(:class_sections,
               column: :id,
               name: "class_exercises_section_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:class_sections) do
      add :name, :text, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "class_sections_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :class_id, :uuid, null: false
    end

    create table(:classes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:class_sections) do
      modify :class_id,
             references(:classes,
               column: :id,
               name: "class_sections_class_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:classes) do
      add :name, :text, null: false
      add :starts_at, :utc_datetime, null: false
      add :ends_at, :utc_datetime, null: false
      add :timezone, :text, null: false, default: "America/New_York"
      add :playlist_name, :text
      add :playlist_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "classes_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :studio_id, :uuid
    end

    create table(:exercises, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:class_exercises) do
      modify :exercise_id,
             references(:exercises,
               column: :id,
               name: "class_exercises_exercise_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:exercises) do
      add :name, :text, null: false
      add :category, :text, null: false
      add :cues, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "exercises_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:starter_imports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "starter_imports_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:starter_imports, [:owner_id],
             name: "starter_imports_one_import_per_owner_index"
           )

    create table(:studios, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:classes) do
      modify :studio_id,
             references(:studios,
               column: :id,
               name: "classes_studio_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:studios) do
      add :name, :text, null: false
      add :address, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "studios_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:studios, "studios_owner_id_fkey")

    alter table(:studios) do
      remove :owner_id
      remove :updated_at
      remove :inserted_at
      remove :address
      remove :name
    end

    drop constraint(:classes, "classes_studio_id_fkey")

    drop constraint(:classes, "classes_owner_id_fkey")

    alter table(:classes) do
      modify :studio_id, :uuid
    end

    drop table(:studios)

    drop constraint(:starter_imports, "starter_imports_owner_id_fkey")

    drop_if_exists unique_index(:starter_imports, [:owner_id],
                     name: "starter_imports_one_import_per_owner_index"
                   )

    drop table(:starter_imports)

    drop constraint(:exercises, "exercises_owner_id_fkey")

    alter table(:exercises) do
      remove :owner_id
      remove :updated_at
      remove :inserted_at
      remove :cues
      remove :category
      remove :name
    end

    drop constraint(:class_exercises, "class_exercises_exercise_id_fkey")

    drop constraint(:class_exercises, "class_exercises_section_id_fkey")

    drop constraint(:class_exercises, "class_exercises_owner_id_fkey")

    alter table(:class_exercises) do
      modify :exercise_id, :uuid
    end

    drop table(:exercises)

    alter table(:classes) do
      remove :studio_id
      remove :owner_id
      remove :updated_at
      remove :inserted_at
      remove :playlist_url
      remove :playlist_name
      remove :timezone
      remove :ends_at
      remove :starts_at
      remove :name
    end

    drop constraint(:class_sections, "class_sections_class_id_fkey")

    drop constraint(:class_sections, "class_sections_owner_id_fkey")

    alter table(:class_sections) do
      modify :class_id, :uuid
    end

    drop table(:classes)

    alter table(:class_sections) do
      remove :class_id
      remove :owner_id
      remove :updated_at
      remove :inserted_at
      remove :position
      remove :name
    end

    alter table(:class_exercises) do
      modify :section_id, :uuid
    end

    drop table(:class_sections)

    drop table(:class_exercises)
  end
end
